#!/bin/sh
# Is adb installed?
[ ! $(which adb) ] && echo "Please install adb!" && exit 1

# Is scrcpy installed?
[ ! $(which scrcpy) ] && echo "Please install scrcpy!" && exit 1

# Is whiptail installed?
[ ! $(which whiptail) ] && echo "Please install whiptail!" && exit 1

whiptail --msgbox "FOR SECURITY REASON, DON'T USE THIS SCRIPT ON PUBLIC WIFI!! Press ENTER to continue" 10 50

# Kill ADB if it's already running
killall adb

# Show some guide message for this script
echo Make sure both of your android phone and your computer
echo is connected to the same discoverable WiFi Network
echo "---"

# Main Part, take the android local IP address and connect it to TCP/IP ADB
adb tcpip 5555
sleep 2
adb shell ip route | awk '{print $9}' | sed -n '1p' | xargs -I{} adb connect {}:5555

# Message to unplug your android phone
sleep 2
whiptail --msgbox "Unplug your Android Phone, Press ENTER to continue!" 10 40
echo "---"

# Open scrcpy
scrcpy -b2M -m800

# Closing message
echo "---"
echo "Great! Have a nice day"
